In [4]:
import sys
print(sys.version)
#For this notebook to work, Python must be 3.6.4 or 3.6.5

import numpy as np
import pandas as pd
from IPython.display import display

from plotnine import *

3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]


In [5]:
#Import Data Set (https://www.kaggle.com/brandao/diabetes)
diabetes=pd.read_csv('Insert the file directory', sep=',')

In [6]:
#Create the output dataset (Y) and feature dataset (X)
X=diabetes.drop(['readmission'], axis = 1)
y=diabetes[['readmission']].values
#checking x column
print('*********************************************************************************')
print('Column names: ',X.columns)
print('*********************************************************************************')
print('Number of rows and columns: ', X.shape)
print('*********************************************************************************')
#checking y column
print(y)
print(y.shape)

*********************************************************************************
Column names:  Index(['los', 'num_lab_procedures', 'num_procedures', 'num_medications',
       'number_outpatient', 'number_emergency', 'number_inpatient',
       'number_diagnoses', 'sex_Female', 'sex_Male', 'age_[0-10)',
       'age_[10-20)', 'age_[20-30)', 'age_[30-40)', 'age_[40-50)',
       'age_[50-60)', 'age_[60-70)', 'age_[70-80)', 'age_[80-90)',
       'age_[90-100)', 'max_glu_serum_>200', 'max_glu_serum_>300',
       'max_glu_serum_None', 'max_glu_serum_Norm', 'A1Cresult_>7',
       'A1Cresult_>8', 'A1Cresult_None', 'A1Cresult_Norm',
       'group_name1_circulatory', 'group_name1_diabetes',
       'group_name1_digestive', 'group_name1_genitourinary',
       'group_name1_injury', 'group_name1_musculoskeletal',
       'group_name1_neoplasms', 'group_name1_other', 'group_name1_respiratory',
       'group_name2_circulatory', 'group_name2_diabetes',
       'group_name2_digestive', 'group_name2_genito

In [7]:
#Split dataset into training and testing, decided on an 80% training and 20% test set
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify = y, test_size=0.20,random_state=0)

In [8]:
#Standardise 
scaler = StandardScaler()
scaler.fit(X_train)
#standardizing both training and test data
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_standardized_train = pd.DataFrame(X_train_scaled, columns = list(X.columns.values))
X_standardized_test = pd.DataFrame(X_test_scaled, columns = list(X.columns.values))

In [9]:
#Training a Logistic Regression using an L1 Regularisation approach and various class weights

from sklearn.linear_model import LogisticRegression
# Case 1 (Yes 80%, No 20%)
dict={'NO': 0.2, 'YES': 0.8}
Log_Reg1 = LogisticRegression(C = 0.01 , penalty = 'l1', class_weight=dict).fit(X_train_scaled, y_train.ravel()) 
# Case 2 (Yes 70%, No 30%)
dict={'NO': 0.3, 'YES': 0.7}
Log_Reg2 = LogisticRegression(C = 0.01 , penalty = 'l1', class_weight=dict).fit(X_train_scaled, y_train.ravel()) 
# Case 3 (Yes 60%, No 40%)
dict={'NO': 0.4, 'YES': 0.6}
Log_Reg3 = LogisticRegression(C = 0.01 , penalty = 'l1', class_weight=dict).fit(X_train_scaled, y_train.ravel()) 

In [10]:
#Outputing Model Metrics

from sklearn import metrics
from sklearn.metrics import f1_score

y_pred= Log_Reg1.predict(X_standardized_test)
confusion = metrics.confusion_matrix(y_test, y_pred)
print("Log_Reg1:\n")
print("Confusion matrix:\n{}".format(confusion))
score = Log_Reg1.score(X_standardized_test, y_test)
print("Accuracy:\n{}".format(score))

y_test_binary = [0 if x=='NO' else 1 for x in y_test]
y_pred_binary = [0 if x=='NO' else 1 for x in y_pred]
f1_score=f1_score(y_test_binary, y_pred_binary, pos_label=1, average='binary') 
print("f1 score:\n{}".format(f1_score))
from sklearn.metrics import classification_report
print(classification_report(y_test_binary, y_pred_binary))
print("Sensitivity=TP/(TP+FN)\n 0.1314")
print("Specificity=TP/(FP+TN)\n 0.969\n")

from sklearn.metrics import f1_score
y_pred= Log_Reg2.predict(X_standardized_test)
confusion = metrics.confusion_matrix(y_test, y_pred)
print("Log_Reg2:\n")
print("Confusion matrix:\n{}".format(confusion))
score = Log_Reg2.score(X_standardized_test, y_test)
print("Accuracy:\n{}".format(score))

y_test_binary = [0 if x=='NO' else 1 for x in y_test]
y_pred_binary = [0 if x=='NO' else 1 for x in y_pred]
f1_score=f1_score(y_test_binary, y_pred_binary, pos_label=1, average='binary') 
print("f1 score:\n{}".format(f1_score))
from sklearn.metrics import classification_report
print(classification_report(y_test_binary, y_pred_binary))
print("Sensitivity=TP/(TP+FN)\n 0.0367")
print("Specificity=TP/(FP+TN)\n 0.995\n")

from sklearn.metrics import f1_score
y_pred= Log_Reg3.predict(X_standardized_test)
confusion = metrics.confusion_matrix(y_test, y_pred)
print("Log_Reg3:\n")
print("Confusion matrix:\n{}".format(confusion))
score = Log_Reg3.score(X_standardized_test, y_test)
print("Accuracy:\n{}".format(score))

y_test_binary = [0 if x=='NO' else 1 for x in y_test]
y_pred_binary = [0 if x=='NO' else 1 for x in y_pred]
f1_score=f1_score(y_test_binary, y_pred_binary, pos_label=1, average='binary') 
print("f1 score:\n{}".format(f1_score))
from sklearn.metrics import classification_report
print(classification_report(y_test_binary, y_pred_binary))
print("Sensitivity=TP/(TP+FN)\n 0.0120")
print("Specificity=TP/(FP+TN)\n 0.999\n")


Log_Reg1:

Confusion matrix:
[[12345   394]
 [ 1090   165]]
Accuracy:
0.8939545519508361
f1 score:
0.1819184123484013
             precision    recall  f1-score   support

          0       0.92      0.97      0.94     12739
          1       0.30      0.13      0.18      1255

avg / total       0.86      0.89      0.88     13994

Sensitivity=TP/(TP+FN)
 0.1314
Specificity=TP/(FP+TN)
 0.969

Log_Reg2:

Confusion matrix:
[[12678    61]
 [ 1209    46]]
Accuracy:
0.9092468200657424
f1 score:
0.06754772393538913
             precision    recall  f1-score   support

          0       0.91      1.00      0.95     12739
          1       0.43      0.04      0.07      1255

avg / total       0.87      0.91      0.87     13994

Sensitivity=TP/(TP+FN)
 0.0367
Specificity=TP/(FP+TN)
 0.995

Log_Reg3:

Confusion matrix:
[[12729    10]
 [ 1240    15]]
Accuracy:
0.910676004001715
f1 score:
0.0234375
             precision    recall  f1-score   support

          0       0.91      1.00      0.95     

#Commentary#

The best model in this example would be: Log_Reg1 where the weights given were the highest for the 'Yes' outcome (Yes 80%, No  20%).
The biggest reason why I chose this model is because the hospital has stated   that the most important issue for this learning algorithm is that it doesn't   miss any patients at risk of being readmitted. Essentially, the model is justified with having  more False Positives then False Negatives as a person's  life is at risk if they are deemed well but are actually in danger. We can see that as the weight for the 'Yes' outcome increased, the number of False Negatives decreased gradually and as a result, the Sensitivity ratio also increased. Also, the Log_Reg1 model is the better overall model as shown by the highest f1 score    (better overall Precision and Recall).